"""Convert the 2026 PDC27 Epoch-1 ADES XML to empyrean-readable ADES PSV.

Field-for-field transcription — no value is rounded, reformatted, or
altered. The only change is structural (XML elements -> one PSV table)
plus dropping <subFmt> (constant "A22"; not a column the reader knows).
Self-verifies: after writing, re-parses both files and asserts every
transcribed field is string-identical.
"""

import hashlib
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).parent
XML_PATH = HERE / "2026pdc27.epoch1.xml"
PSV_PATH = HERE / "astrometry.psv"

EXPECTED_SHA256 = "4a1fccde9c1cb67541e967506c0b9c76ccd724d66799e913e4dfb1cf0d0ef697"

# XML tag -> PSV column, in output order. subFmt deliberately absent.
COLUMNS = [
    "provID",
    "mode",
    "stn",
    "obsTime",
    "ra",
    "dec",
    "rmsRA",
    "rmsDec",
    "astCat",
    "mag",
    "band",
]

HEADER_COMMENT = [
    "SYNTHETIC EXERCISE DATA — this file describes a fictional asteroid",
    "for the IAA PDC 2027 planetary-defense exercise; it is not a real",
    'object. "This is only an exercise." (JPL CNEOS)',
    "Source: https://cneos.jpl.nasa.gov/pd/cs/pdc27/2026pdc27.epoch1.xml",
    "        (Epoch 1 release, 2026-08-01; retrieved 2026-08-13;",
    f"        SHA256 {EXPECTED_SHA256})",
    "Conversion: field-for-field transcription from ADES XML 2022 to",
    "ADES PSV. The constant <subFmt>A22</subFmt> field is dropped;",
    "every other field is carried verbatim. Generated by",
    "convert_pdc27.py, which self-verifies the transcription.",
]


def parse_xml(path: Path) -> list[dict[str, str]]:
    sha = hashlib.sha256(path.read_bytes()).hexdigest()
    if sha != EXPECTED_SHA256:
        sys.exit(f"SHA256 mismatch for {path}: {sha}")
    root = ET.parse(path).getroot()
    assert root.tag == "ades" and root.attrib.get("version") == "2022", root
    records = []
    for opt in root.findall("optical"):
        rec = {child.tag: child.text for child in opt}
        records.append(rec)
    return records


def write_psv(records: list[dict[str, str]], path: Path) -> None:
    lines = ["# version=2022", "# comment"]
    lines += [f"! line {text}" for text in HEADER_COMMENT]
    lines += [
        "# observatory",
        "! mpcCode 500",
        "! name Geocenter (synthetic geocentric astrometry)",
    ]
    lines.append("|".join(COLUMNS))
    for rec in sorted(records, key=lambda r: r["obsTime"]):
        lines.append("|".join(rec[c] for c in COLUMNS))
    path.write_text("\n".join(lines) + "\n")


def verify(records: list[dict[str, str]], path: Path) -> None:
    rows = []
    header = None
    for line in path.read_text().splitlines():
        if line.startswith(("#", "!")) or not line.strip():
            continue
        fields = line.split("|")
        if header is None:
            header = fields
            continue
        rows.append(dict(zip(header, fields)))
    assert header == COLUMNS, header
    assert len(rows) == len(records) == 52, (len(rows), len(records))
    by_time = {r["obsTime"]: r for r in records}
    assert len(by_time) == 52, "duplicate obsTime in source"
    for row in rows:
        src = by_time[row["obsTime"]]
        for col in COLUMNS:
            if row[col] != src[col]:
                sys.exit(
                    f"MISMATCH {row['obsTime']} {col}: "
                    f"psv={row[col]!r} xml={src[col]!r}"
                )
    times = [r["obsTime"] for r in rows]
    assert times == sorted(times), "PSV rows not time-sorted"
    nights = {t[:10] for t in times}
    assert len(nights) == 26, f"expected 26 nights, got {len(nights)}"
    print(
        f"transcription verified: 52/52 rows x {len(COLUMNS)} fields "
        f"string-identical; 26 nights; time-sorted"
    )


if __name__ == "__main__":
    recs = parse_xml(XML_PATH)
    write_psv(recs, PSV_PATH)
    verify(recs, PSV_PATH)
    print(f"wrote {PSV_PATH} ({PSV_PATH.stat().st_size} bytes)")
